### PR TITLE
add a clippy step for ci & resolve clippy lints

### PR DESCRIPTION
**Pull request by cowboy-bebug**
The following lints are resolved (list is [here](https://rust-lang.github.io/rust-clippy/master/)):
- needless_return
- into_iter_on_array
- identity_conversion
- needless_borrow

### CODE REVIEW

**Comment by jordy25519** [comment]
This may help in your quest: https://rust-lang.github.io/rustup-components-history/index.html (may need to bump nightly version to one with clippy)

**Comment by cowboy-bebug** [comment]
Opps I bumped it down to stable Rust altogether lol

**Review by jordy25519 — APPROVED** [review]
LGTM

**Comment by elim0322** [comment]
close #11

**Pull request merged**
